### ISSUE TITLE
Bug: divergence on ETH amount

### ISSUE THREAD

**Issue by lzkill** [Biscoint/biscoint-api-node#21] opened 2021-09-23 12:17 UTC
I'm constantly getting divergence on the ETH amount after buy operations. The amount returned by `confirmOffer` doesn't match the value shown by the app. This behaviour has not been seen on BTC operations yet, suggesting that the new ETH features might be flawed.

![positions](https://user-images.githubusercontent.com/5374593/134504264-849bb7f8-3f29-4a6a-8d90-83d62aa90a8a.png)

![resized-image-Promo](https://user-images.githubusercontent.com/5374593/135249219-2c5721c6-22dd-4b82-9ec5-aca37c521b42.jpeg)

**Comment by bolaum** [comment] 2021-09-23 12:36
Hi @lzkill. Could you walk me through how to reproduce this? Is this related to the API in any way? Values between API requests and what the app returns may vary. 

If you access biscoint.io/dashboard/transactions you can export a detailed report on your operations and get the exact amount for each op.

**Comment by lzkill** [comment] 2021-09-23 13:02
Hi @bolaum.

I haven't found a way to simulate this issue. All my buy operations on Biscoint are done by the API. When the bots are doing their stuff I can see the balance on the app moving up and down, but right now there are no operations being done. Shouldn't the balance match?

Unfortunately, the csv report rounds the ETH amount, so I can't check the divergent decimal places.

![h](https://user-images.githubusercontent.com/5374593/134510560-cd1c775e-1d9b-4b62-8b13-943746020804.png)

My question is: if the api method returned 0.00308315**7696**, why my balance shows only 0.00308315**5528** ETH?

**Comment by bolaum** [comment] 2021-09-23 13:59
@lzkill could you open a ticket in the support (email suporte@biscoint.io)? It is better to discuss details on your account through a private channel. Reply here when you do. Thanks.

**Comment by lzkill** [comment] 2021-09-29 15:17
As discussed with @bolaum the backend is returning '0000' in the baseAmount for ETH sell operations.

Buy offer base amount: 0.002987794858
Buy confirm base amount: 0.002987794858
Sell offer base amount: 0.00298779**0000**
Sell confirm base amount: 0.00298779**0000**

See [this](https://github.com/lzkill/biscoint-test/blob/master/index.js) for a reproducible script.

**Comment by bolaum** [comment] 2021-09-29 15:23
@itxtoledo could you check if this is a lib or backend issue?

**Comment by lzkill** [comment] 2021-09-29 16:05
The temporary hack is truncating the amount on ETH sell offers. The side effect is some ETH residue leftover in the account.

```typescript
  async offer(args: IOfferParams): Promise<IOfferResult> {
    this.truncateEthAmount(args);
    return this.biscoint.offer(args);
  }

  truncateEthAmount(args: IOfferParams) {
    if (!args.isQuote && args.base === 'ETH') {
      args.amount = truncateString(args.amount, 10);
    }

    return args;
  }

truncateString(str, num) {
  if (str.length <= num) {
    return str;
  }
  return str.slice(0, num);
}
```

**Comment by mejnour** [comment] 2021-11-24 15:03
We submitted a new PR that improves consistency. One can now pass 12 decimal places to our API and receive the same.

https://github.com/Biscoint/biscoint-api-node/commit/b1142a8302ac1a1a40ec0f47cb42d3b1e0a54718

**Comment by mejnour** [comment] 2021-11-25 16:35
Closing this issue as it seems to be resolved. Please feel free to open another one in case you find something new. Thanks for contributing!

**Closed as completed by mejnour** 2021-11-25 16:35 UTC

**Comment by lzkill** [comment] 2021-11-26 14:47
I confirm the confirm endpoint conforms.

You guys are awesome! Thanks!

**Comment by lzkill** [comment] 2021-11-26 14:48
I confirm it!

You guys are awesome! Thanks!
